// ReSharper disable CppUnusedIncludeDirective

#ifdef ENABLED_CUDA
#include "cuda.h"
#include "cuda_Core.h"
#include "cuda_GpuMat.h"
#include "cuda_Arithm.h"
#include "cuda_Imgproc.h"
#include "cuda_Warping.h"
#include "cuda_Legacy.h"
#include "cuda_Bgsegm.h"
#include "cuda_Filters.h"
#include "cuda_Stereo.h"
#include "cuda_OpenGL.h"
#include "cuda_Photo.h"
#include "cuda_Stream.h"
#include "cuda_Event.h"
#include "cuda_Bgsegm_gmg.h"
#include "cuda_Bgsegm_mog.h"
#include "cuda_Bgsegm_mog2.h"
#include "cuda_Optflow.h"
#include "cuda_BroxOpticalFlow.h"
#include "cuda_DenseOpticalFlow.h"
#include "cuda_BufferPool.h"
#include "cuda_CannyEdgeDetector.h"
#include "cuda_CascadeClassifier.h"
#endif
